apiVersion: v1
kind: Service
metadata:  
  name: bookstack-http-service
spec:
  selector:    
    app: bookstack
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP